--@description My MIDI Script
--@version 6.9
--@author Gantzy26
--@provides [main] MyScript.lua
--@changelog Initial release
--@about 
--   # My Script
--   This script edits MIDI notes.
--   ## Usage
--   - Select items
--   - Run action
